### ISSUE TITLE
Doesn't manage hosted fonts

### ISSUE THREAD

**Issue by raphaelgoetter** [csstools/postcss-font-magician#1]
Hello,

I'm trying to compile with hosted fonts (`fonts/calendas.woff2` and `fonts/calendas.woff` files)

Here's my input CSS : 

``` css
body {
  font-family: "Calendas";
}
```

Here's my gulpfile.js : 

``` js
...
// Paths
var source = './_src';
var prod = './_dist'; 

gulp.task('font', function () {
  return gulp.src(source + '/assets/css/*.css')
    .pipe(
      postcss([
        require('postcss-font-magician')({
          hosted: source + '/assets/css/fonts'
        })
     ])
    )
    .pipe(
      gulp.dest(prod + '/assets/css')
    );
});
```

My output CSS : 

``` css
body {
  font-family: "Calendas";
}
```

Note : it "works" when I try with `body {font-family: "Alice";}` : Google font is well @font-faced.

But doesn't work with my hosted files :/ 

Did I miss something ?
