### ISSUE TITLE
`options.hosted` should support an array of paths

### ISSUE THREAD

**Issue by MadLittleMods** [csstools/postcss-font-magician#11]
[`options.hosted`](https://github.com/jonathantneal/postcss-font-magician#hosted) should support an array of paths

``` css
require('postcss-font-magician')({
   hosted: [
      '../fonts',
      './assets/fonts'
   ]
});
```
