### ISSUE TITLE
Not loading "Bree Serif"

### ISSUE THREAD

**Issue by robinelvin** [csstools/postcss-font-magician#112]
I have this config:

```javascript
        pfm({
          variants: {
            Raleway: { 300: [], 500: [] },
            "Bree Serif": { 400: [] },
          },
          foundries: ["google"],
        }),
```

And my tailwindcss theme is:

```css
@theme {
    --font-sans: "Raleway", sans-serif;
    --font-serif: "Bree Serif", serif;
}
```

But I am only getting _Raleway_ in my CSS. I have checked my HTML and it is correctly referencing the font:

![Image](https://github.com/user-attachments/assets/c09db1d9-bacd-413c-a38f-be7dcab8f95d)

**Comment by robinelvin** [comment]
I have found the issue. It is not enough to reference the font family in a variable - it needs to be added to CSS class. I experimented with other fonts and they wouldn't load either but I did see my base font always loaded. Searching my codebase I found a single reference in a CSS file. So adding the following to my CSS caused `Bree Serif` to be loaded:

```css
.bogus {
    font-family: "Bree Serif";
}
```

It was not enough to just reference in the `@theme`
