### ISSUE TITLE
Support for cyrillic

### ISSUE THREAD

**Issue by SerjoPepper** [csstools/postcss-font-magician#28]
It seems that current version does not support cyrillic versions for fonts, for example Roboto font has cyrillic version, but I has no way to enable it.

**Comment by Maxpain177** [comment]
+1

**Comment by rajdee** [comment]
@SerjoPepper @Maxpain177
You can use the [unicode-range](https://github.com/jonathantneal/postcss-font-magician#unicode-range) param since version 1.5.0 but I think we need to add support for languages (subsets) from the Google Fonts

**Comment by rajdee** [comment]
@SerjoPepper @Maxpain177 The google fonts subsets was supported in [v2.3.0](https://github.com/jonathantneal/postcss-font-magician/releases/tag/v2.3.0)!

**Comment by Grawl** [comment]
not working for me

```json
{
	"plugins": {
		"postcss-font-magician": {
			"variants": {
				"Roboto Slab": {
					"400": ["local woff woff2", "cyrillic"]
				}
			},
			"foundries": ["google"],
			"display": "swap"
		},
	}
}
```

output:

```css
@font-face {
  font-family: "Roboto Slab";
  font-style: normal;
  font-weight: 400;
  src: local("Roboto Slab Regular"),local(RobotoSlab-Regular),url(//fonts.gstatic.com/s/robotoslab/v9/BngMUXZYTXPIvIBgJJSb6ufD5qM.woff) format("woff"),url(//fonts.gstatic.com/s/robotoslab/v9/BngMUXZYTXPIvIBgJJSb6ufN5qU.woff2) format("woff2");
  font-display: swap;
  unicode-range: U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
}
```

but in browser I see font is not rendered with Roboto Slab

if I do this instead:

```pug
link(rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto+Slab&display=swap&subset=cyrillic')
```

it renders with Roboto Slab
