### ISSUE TITLE
Unicode-range option does nothing

### ISSUE THREAD

**Issue by uqee** [csstools/postcss-font-magician#33]
I'm using an unmodified example from the current readme. Font faces are generated, but without a `unicode-range` properties. Any suggestions?

**Comment by rajdee** [comment]
I checked now and found no errors

```js
 require('postcss-font-magician')({
            variants: {
                'Open Sans': {
                    '300': ["woff eot", "U+0100-024F, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF, U+2C60-2C7F, U+A720-A7FF"],
                    '400 italic': ["eot"]
                }
            },
            foundries: ['google']
        })
```
converted to
```css
@font-face {
    font-family: "Open Sans";
    font-weight: 300;
    font-style: normal;

    src: url(//fonts.gstatic.com/s/opensans/v13/DXI1ORHCpsQm3Vp6mXoaTXhCUOGz7vYGh680lGh-uXM.woff) format("woff"),url(//fonts.gstatic.com/s/opensans/v13/DXI1ORHCpsQm3Vp6mXoaTXZ2MAKAc2x4R1uOSeegc5U.eot?#) format("eot");
    unicode-ranges: U+0100-024F, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF, U+2C60-2C7F, U+A720-A7FF;
}

@font-face {
    font-family: "Open Sans";
    font-weight: 400;
    font-style: italic;

    src: url(//fonts.gstatic.com/s/opensans/v13/xjAJXh38I15wypJXxuGMBmfQcKutQXcIrRfyR5jdjY8.eot?#) format("eot");
}
```
`unicode-range` param works as expected but I plan to rewrite it to add support for languages (subsets) from the Google Fonts.
