### ISSUE TITLE
Hebrew subset doesnt work

### ISSUE THREAD

**Issue by ybelenko** [csstools/postcss-font-magician#42]
From package.json dependencies: `postcss-font-magician: ^1.6.1`

Using with Gulp:
```js
postCssfontmagician({
 variants: {
  'Alef': {
   '700': ['local woff2', 'U+0590-05FF, U+20AA, U+25CC, U+FB1D-FB4F']
  }
 },
 foundries: ['google']
})
```
Expected output:
```css
@font-face {
  font-family: 'Alef';
  font-style: normal;
  font-weight: 700;
  src: local('Alef Bold'), local('Alef-Bold'), url(https://fonts.gstatic.com/s/alef/v6/6FldS2NxdsYYh3OkPr4zA_Y6323mHUZFJMgTvxaG2iE.woff2) format('woff2');
  unicode-range: U+0590-05FF, U+20AA, U+25CC, U+FB1D-FB4F;
}
```
Real output:
```css
@font-face {
  font-family: Alef;
  font-style: normal;
  font-weight: 700;
  src: local("Alef Bold"),local(Alef-Bold),url(//fonts.gstatic.com/s/alef/v6/a_b6i2iOdMAEMhttbuoj2g.woff2) format("woff2");
  unicode-ranges: U+0590-05FF, U+20AA, U+25CC, U+FB1D-FB4F;
}
```
We have `unicode-ranges` param instead of `unicode-range` and completely different links. In summary font-face doesn't work.
